<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateDocumentsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('documents', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('office_id')->unsigned()->index()->comment('id of an office from which a document is originated');
            $table->integer('category_id')->unsigned()->index()->comment('id of a category to which a document belongs');
            $table->foreign('office_id')->references('id')->on('offices');
            $table->foreign('category_id')->references('id')->on('categories');
            $table->string('system_file_name',100)->comment('file name generated by the system for a document');
            $table->string('human_file_name',100)->comment('human readable file name of a document');
            $table->string('file_extension',5)->comment('extension of file for e.g, pdf, doc, jpg etc');
            $table->string('file_size',15)->comment('size of file in a computer machine');
            $table->date('date_of_document')->comment('date of origin of a document');
            $table->text('description')->comment('a brief description of a document');
            $table->text('keywords')->comment('keywords related to a document');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('documents');
    }
}
